import { Resend } from 'resend'
import type { DashboardMetrics, BarberStats } from '@/types'
import { formatCurrency } from './calculations'

const resend = new Resend(process.env.RESEND_API_KEY)
const REPORT_EMAIL = process.env.REPORT_EMAIL || 'Scixxorhand.tm@gmail.com'
const FROM_EMAIL = 'reports@scissorhand.app'

function buildReportHTML(
  title: string,
  period: string,
  metrics: DashboardMetrics,
  barberStats: BarberStats[]
): string {
  const sorted = [...barberStats].sort((a, b) => b.total_revenue - a.total_revenue)

  const barberRows = sorted
    .map(
      (s, i) => `
      <tr style="border-bottom:1px solid #222;">
        <td style="padding:10px 8px;color:#C9A84C;font-weight:700;">#${i + 1}</td>
        <td style="padding:10px 8px;">${s.barber.name}</td>
        <td style="padding:10px 8px;">${formatCurrency(s.total_revenue)}</td>
        <td style="padding:10px 8px;">${s.total_clients}</td>
        <td style="padding:10px 8px;">${formatCurrency(s.total_tips)}</td>
        <td style="padding:10px 8px;">${formatCurrency(s.avg_ticket)}</td>
      </tr>`
    )
    .join('')

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="background:#0a0a0a;color:#f5f5f5;font-family:'Helvetica Neue',Arial,sans-serif;margin:0;padding:0;">
  <div style="max-width:680px;margin:0 auto;padding:40px 20px;">

    <!-- Header -->
    <div style="border-bottom:1px solid #C9A84C;padding-bottom:24px;margin-bottom:32px;">
      <div style="color:#C9A84C;font-size:11px;letter-spacing:3px;text-transform:uppercase;margin-bottom:8px;">✂ SCISSORHAND</div>
      <h1 style="margin:0;font-size:28px;font-weight:300;">${title}</h1>
      <p style="margin:4px 0 0;color:#888;font-size:14px;">${period}</p>
    </div>

    <!-- Key Metrics -->
    <div style="display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin-bottom:32px;">
      ${[
        ['Total Revenue', formatCurrency(metrics.total_revenue)],
        ['Net Revenue', formatCurrency(metrics.net_revenue)],
        ['Cash Collected', formatCurrency(metrics.cash_revenue)],
        ['Tap Collected', formatCurrency(metrics.tap_revenue)],
        ['Total Tips', formatCurrency(metrics.total_tips)],
        ['HST Collected', formatCurrency(metrics.hst_collected)],
        ['Clients Served', metrics.total_clients.toString()],
        ['Services Done', metrics.total_services.toString()],
      ]
        .map(
          ([label, value]) => `
        <div style="background:#111;border:1px solid #222;border-radius:8px;padding:16px;">
          <div style="color:#888;font-size:11px;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;">${label}</div>
          <div style="font-size:22px;font-weight:600;color:#f5f5f5;">${value}</div>
        </div>`
        )
        .join('')}
    </div>

    <!-- Barber Rankings -->
    <div style="margin-bottom:32px;">
      <h2 style="font-size:14px;letter-spacing:2px;text-transform:uppercase;color:#C9A84C;margin-bottom:16px;">Barber Rankings</h2>
      <table style="width:100%;border-collapse:collapse;font-size:14px;">
        <thead>
          <tr style="border-bottom:1px solid #333;">
            <th style="padding:8px;text-align:left;color:#888;">#</th>
            <th style="padding:8px;text-align:left;color:#888;">Barber</th>
            <th style="padding:8px;text-align:left;color:#888;">Revenue</th>
            <th style="padding:8px;text-align:left;color:#888;">Clients</th>
            <th style="padding:8px;text-align:left;color:#888;">Tips</th>
            <th style="padding:8px;text-align:left;color:#888;">Avg Ticket</th>
          </tr>
        </thead>
        <tbody>${barberRows}</tbody>
      </table>
    </div>

    <!-- Footer -->
    <div style="border-top:1px solid #222;padding-top:20px;color:#555;font-size:12px;text-align:center;">
      Generated by Scissorhand · ${new Date().toLocaleString('en-CA', { timeZone: 'America/Toronto' })}
    </div>
  </div>
</body>
</html>`
}

export async function sendDailyReport(
  metrics: DashboardMetrics,
  barberStats: BarberStats[],
  dateLabel: string
) {
  const html = buildReportHTML('Daily Report', dateLabel, metrics, barberStats)
  return resend.emails.send({
    from: FROM_EMAIL,
    to: REPORT_EMAIL,
    subject: `✂ Daily Report — ${dateLabel}`,
    html,
  })
}

export async function sendWeeklyReport(
  metrics: DashboardMetrics,
  barberStats: BarberStats[],
  dateLabel: string
) {
  const html = buildReportHTML('Weekly Report', dateLabel, metrics, barberStats)
  return resend.emails.send({
    from: FROM_EMAIL,
    to: REPORT_EMAIL,
    subject: `✂ Weekly Report — ${dateLabel}`,
    html,
  })
}

export async function sendMonthlyReport(
  metrics: DashboardMetrics,
  barberStats: BarberStats[],
  dateLabel: string
) {
  const html = buildReportHTML('Monthly Report', dateLabel, metrics, barberStats)
  return resend.emails.send({
    from: FROM_EMAIL,
    to: REPORT_EMAIL,
    subject: `✂ Monthly Report — ${dateLabel}`,
    html,
  })
}
